# Generated by Django 3.1.7 on 2021-03-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20210303_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises',
            old_name='deadline',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='exercises',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='student_No',
            field=models.DecimalField(decimal_places=9, max_digits=610399300, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='definition',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='definition',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
