# Generated by Django 3.1.7 on 2021-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20210303_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sending_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('upload_response', models.FileField(null=True, upload_to='Responses')),
            ],
        ),
        migrations.CreateModel(
            name='Watching_Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('dete_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Upload_Exercises',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Upload_Videos',
        ),
    ]
