# Generated by Django 3.1.7 on 2021-03-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20210304_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_exercises',
            name='score',
        ),
        migrations.RemoveField(
            model_name='upload_exercises',
            name='student_No',
        ),
        migrations.AddField(
            model_name='sending_response',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='sending_response',
            name='student_No',
            field=models.DecimalField(decimal_places=9, max_digits=610399300, null=True),
        ),
    ]
