# Generated by Django 3.1.7 on 2021-03-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20210304_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='student_No',
            field=models.DecimalField(decimal_places=0, max_digits=610399300),
        ),
    ]
