# Generated by Django 3.1.7 on 2021-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20210304_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.RenameField(
            model_name='sending_response',
            old_name='upload_response',
            new_name='response',
        ),
        migrations.AddField(
            model_name='sending_response',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='sending_response',
            name='student_No',
            field=models.DecimalField(decimal_places=0, max_digits=610399300, null=True),
        ),
    ]
