# Generated by Django 3.1.7 on 2021-03-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_auto_20210306_0512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sending_Response',
            new_name='Send_Response',
        ),
        migrations.RenameModel(
            old_name='Watching_Videos',
            new_name='Watch_Videos',
        ),
        migrations.AddField(
            model_name='exercises',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
