# Generated by Django 3.1.7 on 2021-03-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_auto_20210306_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('response', models.FileField(upload_to='response')),
            ],
        ),
        migrations.DeleteModel(
            name='Send_Response',
        ),
    ]
