# Generated by Django 3.1.7 on 2021-03-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_auto_20210306_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='date',
        ),
    ]
