# Generated by Django 3.1.7 on 2021-03-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_remove_responses_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='title',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='responses',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
