# Generated by Django 3.1.7 on 2021-03-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_auto_20210306_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='response',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='responses',
            old_name='caption',
            new_name='title',
        ),
    ]
